### ISSUE TITLE
Nested repeater duplication also duplicates parent repeater.

### ISSUE THREAD

**Issue by KingWebsites** [mcguffin/acf-duplicate-repeater#1] opened 2017-12-14 17:54 UTC
Hi, great plugin. It does seem to copy all the types of fields I have, including some ones I'm injecting with custom values.

My issues is that I have two main repeater fields. The main one is called 'Room', and inside this I have a repeater called 'Window' - it's for a window repair man.

If I click the new 'Duplicate Entry' button to the side of the inner repeater, 'Window', I get some strange behavior.

So I have:

Room
 -- Window

I click the Duplicate button next to Window and it works and looks fine:

Room
 -- Window
 -- Window (duplicate)

BUT after I save the page it reloads and shows me:

Room
 -- Window
Room (new)
 -- Window (duplicate)

Is there any chance you could take a look at this?

**Comment by mcguffin** [comment] 2017-12-16 22:00
Hi, 
I had a short look at this, but I couldn't reproduce it.
Can you post the json export file of your field group for a closer look?

This is the one I tested with: https://gist.github.com/mcguffin/a105c1e6406ead2029b00979c26513b7
For you too?

**Comment by shazzygh** [comment] 2017-12-27 01:04
I can confirm I have the same issue. I will attach my json export as a text file
[group_5a2db6af00e7c.txt](https://github.com/mcguffin/acf-duplicate-repeater/files/1588098/group_5a2db6af00e7c.txt)
, please note my custom post type is called "abfahrt" (see location ruleset).

Steps to reproduce:
1. Create new post
2. Leave all fields empty / don't touch fields
3. Duplicate nested row

Can reproduce it 100% of the time this way.

[group_5a2db6af00e7c.txt](https://github.com/mcguffin/acf-duplicate-repeater/files/1588099/group_5a2db6af00e7c.txt)

**Comment by mcguffin** [comment] 2018-02-12 16:46
fixed in 0.1.6
That was an interesting one :)

**Closed** 2018-02-12 16:46 UTC
